######################################################################
# Automatically generated by qmake (2.01a) sø 22. maj 15:44:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src src\GUI src\riclib src\GUI\rapidxml src\GUI\ricobjectview
INCLUDEPATH += .

# Input
HEADERS += src/GUI/about.h \
           src/GUI/mainwindow.h \
           src/GUI/nxtCanvasWidget.h \
           src/GUI/programSettings.h \
           src/GUI/ric_value.h \
           src/GUI/ricfile_widget.h \
           src/GUI/ricObjectModel.h \
           src/GUI/ricParametersModel.h \
           src/riclib/nxtCanvas.h \
           src/riclib/nxtConstants.h \
           src/riclib/nxtCopyOptions.h \
           src/riclib/nxtVariable.h \
           src/riclib/nxtVarRicCopyOptions.h \
           src/riclib/nxtVarRicWord.h \
           src/riclib/pointArray.h \
           src/riclib/ricfile.h \
           src/riclib/ricObject.h \
           src/GUI/rapidxml/rapidxml.hpp \
           src/GUI/rapidxml/rapidxml_iterators.hpp \
           src/GUI/rapidxml/rapidxml_print.hpp \
           src/GUI/rapidxml/rapidxml_utils.hpp \
           src/GUI/ricobjectview/copyoptions_value.h \
           src/GUI/ricobjectview/nxtCanvasEdit.h \
           src/GUI/ricobjectview/nxtVarWordValue.h \
           src/GUI/ricobjectview/ricobject_abstract.h \
           src/GUI/ricobjectview/ricobject_circle.h \
           src/GUI/ricobjectview/ricobject_container.h \
           src/GUI/ricobjectview/ricobject_copybits.h \
           src/GUI/ricobjectview/ricobject_description.h \
           src/GUI/ricobjectview/ricobject_ellipse.h \
           src/GUI/ricobjectview/ricobject_line.h \
           src/GUI/ricobjectview/ricobject_point.h \
           src/GUI/ricobjectview/ricobject_rect.h \
           src/GUI/ricobjectview/ricobject_sprite.h \
           src/GUI/ricobjectview/spriteValue.h
FORMS += src/GUI/about.ui \
         src/GUI/mainwindow.ui \
         src/GUI/ric_value.ui \
         src/GUI/ricfile.ui \
         src/GUI/ricobjectview/copyoptions_value.ui \
         src/GUI/ricobjectview/spriteValue.ui
SOURCES += src/main.cpp \
           src/GUI/about.cpp \
           src/GUI/mainwindow.cpp \
           src/GUI/nxtCanvasWidget.cpp \
           src/GUI/programSettings.cpp \
           src/GUI/ric_value.cpp \
           src/GUI/ricfile_widget.cpp \
           src/GUI/ricObjectModel.cpp \
           src/GUI/ricParametersModel.cpp \
           src/riclib/nxtCanvas.cpp \
           src/riclib/nxtVariable.cpp \
           src/riclib/nxtVarRicWord.cpp \
           src/riclib/pointArray.cpp \
           src/riclib/ricfile.cpp \
           src/riclib/ricObjectDraw.cpp \
           src/riclib/ricObjectRead.cpp \
           src/riclib/ricObjectWrite.cpp \
           src/GUI/ricobjectview/copyoptions_value.cpp \
           src/GUI/ricobjectview/nxtCanvasEdit.cpp \
           src/GUI/ricobjectview/nxtVarWordValue.cpp \
           src/GUI/ricobjectview/ricobject_abstract.cpp \
           src/GUI/ricobjectview/ricobject_circle.cpp \
           src/GUI/ricobjectview/ricobject_container.cpp \
           src/GUI/ricobjectview/ricobject_copybits.cpp \
           src/GUI/ricobjectview/ricobject_description.cpp \
           src/GUI/ricobjectview/ricobject_ellipse.cpp \
           src/GUI/ricobjectview/ricobject_line.cpp \
           src/GUI/ricobjectview/ricobject_point.cpp \
           src/GUI/ricobjectview/ricobject_rect.cpp \
           src/GUI/ricobjectview/ricobject_sprite.cpp \
           src/GUI/ricobjectview/spriteValue.cpp
